Steam/Controllers/LegalInfomationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Steam.Controllers
{
    public class LegalInfomationController : Controller
    {
        // GET: LegalInfomation
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult VideoPolicy()
        {
            return View();
        }
        public ActionResult PrivacyPolicyAgreement()
        {
            return View();
        }
        public ActionResult SteamSubscriberAgreement()
        {
            return View();
        }
        public ActionResult SteamRefunds()
        {
            return View();
        }
        public ActionResult RefundList()
        {
            return View();
        }
    }
}

Steam/Views/LegalInfomation/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render(@"~\Content\bootstrap.min.css")
@Styles.Render(@"~\Content\CSS\hrBackground.css")
@Styles.Render("~/Content/css")
<div id="container">
    <h1 id="title">LEGAL INFO</h1>
    <hr class="hrLine" />
    <div id="content" class=".col-md-4 .col-md-offset-2">
        <p>
            <h4>COPYRIGHT</h4>
        <p>
            © 2019 Valve Corporation. All rights reserved.
            Valve, the Valve logo, Half-Life, the Half-Life logo,
            the Lambda logo, Steam, the Steam logo, Team Fortress,
            the Team Fortress logo, Opposing Force, Day of Defeat,
            the Day of Defeat logo, Counter-Strike, the Counter-Strike logo,
            Source, the Source logo, Counter-Strike: Condition Zero, Portal, the Portal logo, Dota, the Dota 2 logo, and Defense of the Ancients are trademarks and/or registered trademarks of Valve Corporation.
            All other trademarks are property of their respective owners.
        </p>
        <p>
            <h4>VALVE VIDEO POLICY</h4>
        <p>@Html.ActionLink("Click here for information.", "VideoPolicy", "LegalInfomation")</p>
        </p>
        <p>
        <p>
            <h4>THIRD PARTY LEGAL NOTICES</h4>
        </p>
        <p>
            Steam and other Valve products distributed via Steam
            use certain third party materials that require notifications
            about their license terms. You can find a list of these
            notifications in the file called ThirdPartyLegalNotices.doc
            distributed with the Steam client and/or a particular Valve
            product. Where license terms require Valve to make source code
            available for redistribution,
            the code may be found
            <a href="https://developer.valvesoftware.com/wiki/Category:Valve_Open_Source">here</a>.
        </p>
        </p>
        <p>
            <h4>CLAIMS OF COPYRIGHT INFRINGEMENT</h4>
        <p>
            Valve respects the intellectual property rights of others,
            and we ask that everyone using our internet sites and services
            do the same. Anyone who believes that their work has been reproduced
            in one of our internet sites or services in a way that constitutes
            copyright infringement may notify Valve via our contact page.
        </p>
        <p>More information about U.S. copyright law can be found at the <a href="http://lcweb.loc.gov/copyright/">United States Copyright Office</a> </p>
        </p>

    </div>
</div>

Steam/Views/LegalInfomation/RefundList.cshtml
@{
    ViewBag.Title = "RefundList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render(@"~\Content\bootstrap.min.css")
@Styles.Render(@"~\Content\CSS\hrBackground.css")
@Styles.Render("~/Content/css")
<div id="container">
    <h1 id="title">STEAM REFUNDS</h1>
    <h3 style="color:white;">Payment Methods</h3>
    <hr class="hrLine" />
    <div id="content" class=".col-md-4 .col-md-offset-2">
        <p>
            Some payment methods available through Steam do not support refunding a purchase back to the original payment method. For these purchases, refunds can only be issued to the user's Steam Wallet.
        </p>
        <p>
            In your country, the following payment methods support refunds:
        </p>
        <ul style="list-style-type:circle">
            <li>PayPal</li>
            <li>Visa</li>
            <li>MasterCard</li>
            <li>American Express</li>
            <li>JCB</li>
        </ul>
        <p>For more information about refunds on Steam, please see the @Html.ActionLink("Steam Refunds page", "SteamRefunds", "LegalInfomation").</p>
    </div>
</div>

Steam/Views/LegalInfomation/SteamRefunds.cshtml
@{
    ViewBag.Title = "SteamRefunds";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render(@"~\Content\bootstrap.min.css")
@Styles.Render(@"~\Content\CSS\hrBackground.css")
@Styles.Render("~/Content/css")
<style>
    h4{
        color:white;
        font-weight:100;
    }
</style>
<div id="container">
    <h1 id="title">STEAM REFUNDS</h1>
    <hr class="hrLine" />
    <div id="content" class=".col-md-4 .col-md-offset-2">
        <p>
            You can request a refund for nearly any purchase on Steam—for any reason. Maybe your PC doesn't meet the hardware requirements; maybe you bought a game by mistake; maybe you played the title for an hour and just didn't like it.
        </p>
        <p>
            It doesn't matter. Valve will, issue a refund for any reason, if the request is made within the required return period, and, in the case of games, if the title has been played for less than two hours. There are more details below, but even if you fall outside of the refund rules we’ve described, you can ask for a refund anyway and we’ll take a look.
        </p>
        <p>
            You will be issued a full refund of your purchase within a week of approval. You will receive the refund in Steam Wallet funds or through the same payment method you used to make the purchase. If, for any reason, Steam is unable to issue a refund via your initial payment method, your Steam Wallet will be credited the full amount. (Some payment methods available through Steam in your country may not support refunding a purchase back to the original payment method. @Html.ActionLink("Click here for a full list.","RefundList", "LegalInfomation"))
        </p>
        <h2>Where Refunds Apply</h2>
        <p>
            The Steam refund offer, within two weeks of purchase and with less than two hours of playtime, applies to games and software applications on the Steam store. Here is an overview of how refunds work with other types of purchases.
        </p>
        <h4>
            REFUNDS ON DOWNLOADABLE CONTENT</br>
            (STEAM STORE CONTENT USABLE WITHIN ANOTHER GAME OR SOFTWARE APPLICATION, "DLC")
        </h4>
        <p>
            DLC purchased from the Steam store is refundable within fourteen days of purchase, and if the underlying title has been played for less than two hours since the DLC was purchased, so long as the DLC has not been consumed, modified or transferred. Please note that in some cases, Steam will be unable to give refunds for some third party DLC (for example, if the DLC irreversibly levels up a game character). These exceptions will be clearly marked as nonrefundable on the Store page prior to purchase.
        </p>
        <h4>REFUNDS ON IN-GAME PURCHASES</h4>
        <p>
            Steam will offer refund for in-game purchases within any Valve-developed games within forty-eight hours of purchase, so long as the in-game item has not been consumed, modified or transferred. Third-party developers will have the option to enable refunds for in-game items on these terms. Steam will tell you at the time of purchase if the game developer has opted to offer refunds on the in-game item you are buying. Otherwise, in-game purchases in non-Valve games are not refundable through Steam.
        </p>
        <h4>REFUNDS ON PRE-PURCHASED TITLES</h4>
        <p>
            When you pre-purchase a title on Steam (and have paid for the title in advance), you can request a refund at any time prior to release of that title. The standard 14-day/two-hour refund period also applies, starting on the game’s release date.
        </p>
        <h4>STEAM WALLET REFUNDS</h4>
        <p>You may request a refund for Steam Wallet funds within fourteen days of purchase if they were purchased on Steam and if you have not used any of those funds.</p>
        <h4>STEAM HARDWARE</h4>
        <p>
            Within the applicable time frame identified in the Hardware Refund Policy, you may request a refund for Steam hardware and accessories purchased via Steam for any reason. You must ship the hardware back to us within fourteen (14) days after requesting the refund, following the instructions we provide you. Please see the Hardware Refund Policy for detailed guidelines on the return and cancellation process for Steam hardware and accessories.
        </p>
        <h4>REFUNDS ON BUNDLES</h4>
        <p>
            You can receive a full refund for any bundle purchased on the Steam Store, so long as none of the items in the bundle have been transferred, and if the combined usage time for all items in the bundle is less than two hours. If a bundle includes an in-game item or DLC that is not refundable, Steam will tell you if the whole bundle is refundable during check-out.
        </p>
        <h4>PURCHASES MADE OUTSIDE OF STEAM</h4>
        <p>
            Valve cannot provide refunds for purchases made outside of Steam (for example, CD keys or Steam wallet cards purchased from third parties).
        </p>
        <h4>VAC BANS</h4>
        <p>
            If you have been banned by VAC (the Valve Anti-Cheat system) on a game, you lose the right to refund that game.
        </p>
        <h4>VIDEO CONTENT</h4>
        <p>
            We are unable to offer refunds for video content on Steam (e.g. movies, shorts, series, episodes, and tutorials), unless the video is in a bundle with other (non-video) refundable content.
        </p>
        <h4>REFUNDS ON GIFTS</h4>
        <p>
            Unredeemed gifts may be refunded within the standard 14-day/two-hour refund period. Redeemed gifts may be refunded under the same conditions if the gift recipient initiates the refund. Funds used to purchase the gift will be returned to the original purchaser.
        </p>
        <h4>ABUSE</h4>
        <p>
            Refunds are designed to remove the risk from purchasing titles on Steam—not as a way to get free games. If it appears to us that you are abusing refunds, we may stop offering them to you. We do not consider it abuse to request a refund on a title that was purchased just before a sale and then immediately rebuying that title for the sale price.
        </p>
        <p>Last updated 30 April, 2019</p>
    </div>

</div>

Steam/Views/LegalInfomation/VideoPolicy.cshtml
@{
    ViewBag.Title = "VideoPolicy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render(@"~\Content\CSS\hrBackground.css")
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<div id="container">
    <h1 id="title">VIDEO POLICY</h1>
    <hr class="hrLine" />
    <div id="content" class=".col-md-6 .col-md-offset-2">
        <p>
            <h4>VALVE VIDEO POLICY</h4>
        <p>
            We encourage our users to make videos using
            Valve game content, such as playthrough or
            instruction videos or SFM movies. We are fine
            with publishing these videos to your website or
            YouTube or similar video sharing services. We're
            not fine with taking assets from our games
            (e.g. voice, music, items) and distributing
            those separately.
        </p>
        <p>
            Use of our content in videos must be non-commercial.
            By that we mean you can't charge users to view or
            access your videos. You also can't sell or license
            your videos to others for a payment of any kind.
        </p>
        <p>
            You are free to monetize your videos
            via the YouTube partner program and similar
            programs on other video sharing sites. Please
            don't ask us to write YouTube and tell them its
            fine with us to post a particular video using
            Valve content. It's not possible to respond to
            each such request. Point them to this page.
        </p>
        <p>
            Of course this policy applies only to Valve content.
            If you include someone else's content in your video,
            such as music, you will have to get permission from
            the owner.
        </p>
        <p>
            @Html.ActionLink("Back to Valve Legal Info", "Index", "LegalInfomation")
        </p>
        </p>

    </div>
</div>

@*Scripts.Render("~/bundles/bootstrap")*@